# zag.mod — Zag project lockfile (REQUIRED at project root).
# Generated by `zagc init`. Pins the toolchain this project builds under,
# so a future zagc can refuse to silently miscompile legacy sources.
name = "zag-poc-examples"

[toolchain]
# Caret constraint: any compatible compiler within the 0.1 series.
zag     = "^0.1.0"
# Language edition — the syntax/semantics contract. Hard compatibility boundary.
edition = "phase0"
# Exact build this lockfile was generated against (informational pin).
commit  = "poc-phase0"

[features]
# Compiler capabilities this project relies on. Build fails fast if a
# future/older zagc cannot honor one of these.
require = ["effects", "generics", "interfaces", "hotreload"]
