#!/usr/bin/env bash
# Generate the driver support matrix from executable evidence markers.
set -eu
cd "$(dirname "$0")/.."
evidence=${ZAG_DRIVER_EVIDENCE_DIR:-"$PWD/.driver-evidence"}

status() {
  if [ -f "$evidence/$1" ]; then
    printf 'supported'
  else
    printf 'blocked'
  fi
}

printf '%s\n\n' '# Generated Zag driver support matrix'
printf '%s\n\n' 'Generated by `tests/generate_driver_support_matrix.sh`; do not edit manually.'
printf '%s\n' '| Kernel series | Target | Shared core lowering | Userspace adapter | Kbuild handoff | Kernel module | QEMU boot/load/unload | Emulator | Physical devices |'
printf '%s\n' '|---|---|---:|---:|---:|---:|---:|---:|---:|'
for series in 6_1 6_6; do
  for target in x86_64 arm64 i686; do
    printf '| Linux %s | %s | %s | %s | %s | %s | %s | %s | unavailable |\n' \
      "${series/_/.}" "$target" \
      "$(status "core_${series}_${target}.pass")" \
      "$(status "userspace_${series}_${target}.pass")" \
      "$(status "kbuild_${series}_${target}.pass")" \
      "$(status "module_${series}_${target}.pass")" \
      "$(status "qemu_${series}_${target}.pass")" \
      "$(status emulator.pass)"
  done
done
