#!/usr/bin/env bash
# Render the v2 release-gate inventory from the authoritative test script.
# This describes gate status categories, not feature completion.
set -eu
cd "$(dirname "$0")/.."
gate=tests/run_v2_release_gate.sh
printf '%s\n' '# Generated v2 release-gate support matrix'
printf '%s\n\n' 'Generated by `bash tests/generate_v2_support_matrix.sh`; do not edit manually.'
printf '%s\n' '| Category | Gate status | Evidence source |'
printf '%s\n' '|---|---|---|'
sed -n 's/^run_gate "\([^"]*\)".*/| \1 | Required test gate: PASS only when its command exits 0 |/p' "$gate"
sed -n 's/^unsupported "\([^"]*\)" "\([^"]*\)"/| \1 | REQUIRED FAILURE: UNSUPPORTED — \2 |/p' "$gate"
