#!/usr/bin/env bash
# Render the frozen ZagScript 1.0 capability contract from its TSV authority.
set -euo pipefail
cd "$(dirname "$0")/.."
matrix=tests/zagscript_1_0_capabilities.tsv

printf '%s\n\n' '# ZagScript 1.0 capability matrix'
printf '%s\n\n' 'Generated by `bash tests/generate_zagscript_1_0_matrix.sh`; do not edit manually.'
printf '%s\n\n' 'Linux x86-64 is the first authority. A 1.0 release requires every row to be `supported` by executable evidence.'
printf '%s\n' '| Area | Capability | Status | Evidence or blocker |'
printf '%s\n' '|---|---|---|---|'
tail -n +2 "$matrix" | while IFS=$'\t' read -r area capability status evidence; do
    printf '| %s | %s | `%s` | %s |\n' "$area" "$capability" "$status" "$evidence"
done
