# Pure-Zag driver object handoff fixture.
# The payload named by ZAG_DRIVER_PREBUILT is generated by Zag. Kbuild owns
# the copy metadata, composite relocatable link, modpost, module metadata, and
# final .ko link. No C, C++, or assembly driver source is part of this boundary.
obj-m := zag_driver.o
zag_driver-objs := zag_payload.o

quiet_cmd_zag_payload = ZAG     $@
      cmd_zag_payload = cp $(ZAG_DRIVER_PREBUILT) $@

$(obj)/zag_payload.o: $(ZAG_DRIVER_PREBUILT) FORCE
	$(call if_changed,zag_payload)
